name = "fora-api"
main = "worker/index.ts"
compatibility_date = "2026-05-16"

compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "fora-prod"
database_id = "188fdc2d-c0db-466b-9ddc-e143ffa18d64"
